server:
  port: 9586
  servlet:
    context-path: "/playqd"

spring:
  datasource:
    url: "jdbc:hsqldb:mem:playsqd_db"
    username: bemonovoid
    password: bemonovoidpwd
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true