spring:
  datasource:
    url: "jdbc:hsqldb:hsql://localhost:9004/playqd_db"
    username: bemonovoid
    password: bemonovoidpwd
    type: org.hsqldb.jdbc.JDBCPool
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.HSQLDialect"

playqd:
  channel:
    repeatAll: true
  library:
    source:
      local:
        - "D:/Music/Coldplay"
        - "D:/Music/Foals"
logging:
  level:
    org.springframework.jdbc.core: TRACE
    org.hsqldb: TRACE
