spring:
  datasource:
    url: "jdbc:hsqldb:hsql://localhost:9004/playio_db"
    username: bemonovoid
    password: bemonovoidpwd
    type: org.hsqldb.jdbc.JDBCPool

playio:
  library:
    source:
      local:
        - "D:/Music/Coldplay"
        - "D:/Music/Foals"
