server:
  port: 9586
  servlet:
    context-path: "/playio"

spring:
  datasource:
    url: "jdbc:hsqldb:mem:playio_db"
    username: playio
    password: playio
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true